### ISSUE TITLE
comments not showing up after re-export of cognate sets

### ISSUE THREAD

**Issue by nataliacp** [Anaphory/lexedata#34]
Only  5 comments show up in the latest Arawak export and all of them were initially notes in the google doc. 
I checked that both google notes and comments make it to the xlsx file that is downloaded, but then only original notes make it out from the exporter. 
so it should be the thing reading xlsx comments that is not working on all of them. 
A good test case is ARM1 that has both a note and a comment: 
In the google spreadsheet: the note is "an ana\~tana set. -- LDM".  The comment has essentially identical text "AR O: an ana\~tana set. -- LDM", it has been resolved and then reopened (all by Lev). 
In the downloaded xlsx file: both note and comment are merged as following: 
![image](https://user-images.githubusercontent.com/6968888/97497712-38331900-196b-11eb-9b25-b7be9f153842.png)
In the xlsx file coming out of the exporter, only the original note "an ana\~tana set. -- LDM" is present, without any trace of the comment and its history.

**Comment by Anaphory** [comment]
I believe this is fixed now. @Melvin can you imagine any way to test this without assuming a download from Google Docs?

**Comment by nataliacp** [comment]
it is fixed only for the column that holds the cognate set ID (HEAD1, HEAD2 etc). All comments in other cells of the spreadsheet do not make it out of the loop.

**Comment by nataliacp** [comment]
I think this is still not working for the comments of cognate judgements (unless I messed up the loop somehow)
